package com.example.chatapp.util

object Constants {
    const val IMAGE_URI = "img_uri"
    const val TOKEN = "msgToken"
    const val API_KEY = "key=AAAAdFWvm_s:APA91bHpYNrD-64Tof3Tepd275MqwK-toBYZnnDmPAXYwmU0ilxEbCcm_RDlIrkHlH78w0I01PBkTyGpvlwJKXObJ1E1F2D1aet3WvHMSA1VZ32nEf_QBlIOtU4E_Iy8ZBVTzH1u2_ok"
    const val PARTICIPANTS_NAME = "participant_name"
    const val PARTICIPANTS_PFP = "participant_pfp"
    const val USER_PFP = "user_pfp"
    const val IS_NEW_USER = "newUser"
    const val IMAGE = "image"
    const val SENDER_NAME = "senderName"
    const val CHAT_TYPE = "chatType"
    const val GROUP_NAME = "groupName"
    const val GROUP_ID = "groupId"
    const val GROUPS = "groups"
    const val PARTICIPANTS = "participants"
    const val USERS = "users"
    const val CHATS = "chats"
    const val SENDERID = "senderId"
    const val MESSAGES = "messages"
    const val SENT_TIME = "sentTime"
    const val MESSAGEID = "messageId"
    const val MESSAGE_TYPE = "messageType"
    const val TEXT = "text"
    const val USERNAME = "userName"
    const val ABOUT = "about"
    const val USERID = "userId"
    const val FUID = "fuid"
    const val PFP_URI = "pfpUri"
    const val RC_SELECT_IMAGE = 999
}